### ISSUE TITLE
ValueError: Unsupported char —

### ISSUE THREAD

**Issue by lesp** [pimoroni/microdot-phat#24]
Hello
Tinkering with microdot-phat for a tutorial and noticed that a "-" character is not supported. Code fails on this character every time.
Error text
```
  File "/home/pi/news.py", line 29, in <module>
    lengths[line] = write_string(text, offset_x=offset_left, offset_y=line_height * line)
  File "/usr/lib/python3/dist-packages/microdotphat/__init__.py", line 217, in write_string
    char_data = numpy.array(_get_char(char))
  File "/usr/lib/python3/dist-packages/microdotphat/__init__.py", line 162, in _get_char
    raise ValueError("Unsupported char {}".format(char))
ValueError: Unsupported char —
```
Line 29 is where this happens
```
for line, text in enumerate(lines):
    lengths[line] = write_string(text, offset_x=offset_left, offset_y=line_height * line)
    offset_left += lengths[line]
```
I'm parsing an RSS feed using feedparser and the list I create is working, but second entry in the list has a "-" in the headline. 
Cheers!

**Comment by Gadgetoid** [comment]
From the error message, it looks like the unsupported char is the Em dash `—` versus the minus-sign `-`.

In your case, probably a `replace("—", "-")` would work for the time being, but it looks like this could be added to the font as a copy of "-".

**Comment by lesp** [comment]
Cheers Phil!
